# Generated by Django 5.0.6 on 2024-08-23 15:20

import customers.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_employee_picture_employee_uuid_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=customers.models.employee.Employee.upload_to),
        ),
    ]
