# Generated by Django 5.0.6 on 2024-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_description_order_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('price_in_cents', models.IntegerField()),
            ],
        ),
    ]
